# Generated by Django 3.1.1 on 2020-09-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
